# Generated by Django 5.1.5 on 2025-02-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_type', 'section_number')},
        ),
    ]
