# Generated by Django 5.1.5 on 2025-02-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_section_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
