# Generated by Django 5.1.5 on 2025-02-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_section_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
