# Generated by Django 5.1.5 on 2025-02-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_section_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecture_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='tutorial_required',
            field=models.BooleanField(default=False),
        ),
    ]
