# Generated by Django 5.1.5 on 2025-02-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_lecture_required_course_tutorial_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
