# Generated by Django 5.1.5 on 2025-02-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_max_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
