# Generated by Django 5.1.5 on 2025-02-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollmentcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial')], max_length=10),
        ),
    ]
