# Generated by Django 5.1.5 on 2025-02-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_section_schedule_section_class_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('section', 'week_number')},
        ),
    ]
