# Generated by Django 5.1.5 on 2025-02-13 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_week_number_alter_attendance_date'),
        ('courses', '0012_alter_classsession_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognitionstatus',
            name='week_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='week_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facerecognitionstatus',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'section', 'week_number')},
        ),
        migrations.AlterUniqueTogether(
            name='facerecognitionstatus',
            unique_together={('section', 'week_number')},
        ),
    ]
