# Generated by Django 5.1.5 on 2025-02-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_facerecognitionstatus_week_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecognitionstatus',
            name='week_number',
            field=models.IntegerField(),
        ),
    ]
